site_name: Pipi Guide
docs_dir: 'src'
pages:
- ['index.md', 'Getting Started']

- ['installation/developer-installation.md', 'Installation', 'Developer Installation']
- ['installation/user-installation.md', 'Installation', 'User Installation']
- ['installation/installing-redist.md', 'Installation', 'Installing redist']
- ['installation/installing-python.md', 'Installation', 'Installing Python']
- ['installation/installing-pip.md', 'Installation', 'Installing pip']
- ['installation/installing-git.md', 'Installation', 'Installing git']
- ['installation/installing-pipi.md', 'Installation', 'Installing git']
- ['installation/adding-to-path.md', 'Installation', 'Adding to PATH']
- ['installation/trouble.md', 'Installation', 'Having Trouble']
- ['installation/testing.md', 'Installation', 'Testing']

- ['configuration/overview.md', 'Configuration', 'Overview']
- ['configuration/setting-up-about.md', 'Configuration', 'Setting up About']
- ['configuration/setting-up-dashboard.md', 'Configuration', 'Setting up Dashboard']
- ['configuration/registering-software.md', 'Configuration', 'Registering software']
- ['configuration/adding-software.md', 'Configuration', 'Adding software']
- ['configuration/adding-new-workspace.md', 'Configuration', 'Adding a new workspace']
- ['configuration/running-software.md', 'Configuration', 'Running software']
- ['configuration/configuring-software.md', 'Configuration', 'Configuring software']
- ['configuration/non-available-software.md', 'Configuration', 'Non-available software']
- ['configuration/cross-platform.md', 'Configuration', 'Cross-platform']
- ['configuration/missing.md', 'Configuration', 'Missing functionality']
- ['configuration/using-openmetadata.md', 'Configuration', 'Using Open Metadata']

# - ['user-guide/first-steps.md', 'User Guide', 'First Steps']
- ['user-guide/reference.md', 'User Guide', 'Reference']
- ['user-guide/api.md', 'User Guide', 'API']
- ['user-guide/faq.md', 'User Guide', 'FAQ']

- ['contributing.md', 'Contributing']
- ['about.md', 'About', 'About']
- ['index-alt.md', 'About', 'Alternative Index']
# theme_dir: 'theme'
theme: 'bootstrap'
# theme: cerulean
# theme: cosmo
# theme: cyborg
# theme: slate